export default {
  tasks: [
    {
      _id: 1,
      title: 'Curso online',
      content: 'Platzi, Udemy o Youtube',
      initialHour: 13,
      finalHour: 15,
      days: ['all'],
      prioridad: 'alta',
      isComplete: false,
    },
    {
      _id: 2,
      title: 'Proyecto Personal',
      content: 'Avanzar en el gestor de tareas',
      initialHour: 10.3,
      finalHour: 13,
      days: ['all'],
      prioridad: 'alta',
      isComplete: true,
    },
    {
      _id: 3,
      title: 'Entrenamiento de algoritmos',
      content: 'Practicar durante 1 hora en leetcode',
      initialHour: 16,
      finalHour: 17,
      days: ['all'],
      prioridad: 'alta',
      isComplete: false,
    },
    {
      _id: 4,
      title: 'Comida',
      content: 'Comida',
      initialHour: 15,
      finalHour: 16,
      days: ['all'],
      prioridad: 'alta',
      isComplete: false,
    },
    {
      _id: 5,
      title: 'Limpieza',
      content: 'Limpiar el cuarto',
      initialHour: 17,
      finalHour: 17.3,
      days: ['all'],
      prioridad: 'alta',
      isComplete: false,
    },
    {
      _id: 6,
      title: 'Ducha',
      content: 'Ducharse',
      initialHour: 10,
      finalHour: 10.3,
      days: ['all'],
      prioridad: 'alta',
      isComplete: false,
    },
    {
      _id: 7,
      title: 'Elsword',
      content: 'Elsword',
      time: ['0-1'],
      initialHour: 0,
      finalHour: 1,
      days: ['all'],
      prioridad: 'alta',
      isComplete: false,
    },
    {
      _id: 8,
      title: 'Ejercicio',
      content: 'Ejercicio',
      initialHour: 9,
      finalHour: 10,
      days: ['all'],
      prioridad: 'alta',
      isComplete: false,
    },
    {
      _id: 9,
      title: 'Checar las redes sociales',
      content: 'Entrar a facebook, linkedin, twitter para ocio, ofertas y recursos de interes',
      initialHour: 8,
      finalHour: 9,
      days: ['all'],
      prioridad: 'alta',
      isComplete: false,
    },
    {
      _id: 10,
      title: 'Dormir',
      content: 'Dormir',
      initialHour: 1,
      finalHour: 8,
      days: ['all'],
      prioridad: 'alta',
      isComplete: false,
    },
    {
      _id: 11,
      title: 'Curso online',
      content: 'Platzi, Udemy o Youtube',
      initialHour: 17.3,
      finalHour: 21,
      days: ['all'],
      prioridad: 'alta',
      isComplete: false,
    },
    {
      _id: 12,
      title: 'Cena',
      content: 'Cena',
      initialHour: 21,
      finalHour: 22,
      days: ['all'],
      prioridad: 'alta',
      isComplete: false,
    },
    {
      _id: 13,
      title: 'Proyecto Personal',
      content: 'Avanzar en el gestor de tareas',
      initialHour: 22,
      finalHour: 24,
      days: ['all'],
      prioridad: 'alta',
      isComplete: false,
    },
  ],
};
